wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1735783123.428229
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.0
      5: 0.16.0
      8:
      - 4
      - 5
      13: darwin-arm64
input_artifact:
  desc: null
  value: sample.csv:latest
output_artifact:
  desc: null
  value: clean_sample.csv
output_type:
  desc: null
  value: cleaned_data
output_description:
  desc: null
  value: Cleaned data artifact
min_price:
  desc: null
  value: '10'
max_price:
  desc: null
  value: '350'
